/**
 * The ISO 3166-1 country list, typed (PLAN.md D23).
 *
 * `countries.json` is generated by `pnpm gen:countries` and committed. This module is the only
 * thing that reads it, so the shape is asserted once, here, and everything else works with
 * `Country`.
 *
 * **Client-safe on purpose.** No `node:` import, no chain call, no zod: a country select on
 * `/verify` imports this and pays for the data, nothing else. The whole file is ~13 KB of JSON,
 * and only the pages that need it pull it in — the public pages (`/`, `/transparency`) do not.
 *
 * ## `blocked` here is the seed, not the law
 *
 * The marks in `countries.json` are the pair `contracts/script/Deploy.s.sol` passes to the
 * `IdentityRegistry` constructor: 840 (United States) and 792 (Türkiye). The registry's admin can
 * block or unblock any code at any time with `setCountryBlocked`, so **the contract is the
 * authority and this file is not**. Two consequences that the rest of the code depends on:
 *
 *   - The server never approves a request on the strength of this file. `lib/server/chain.ts`
 *     asks the deployed registry `isCountryBlocked(code)` for the country actually submitted, and
 *     that answer decides (COMPLIANCE_RULES.md section 1).
 *   - This list is a *floor*. If the chain cannot be reached, a country marked blocked here is
 *     still refused. Failing that way round can only ever refuse something the contract might
 *     have allowed; the reverse — approving something the contract blocks — is the failure that
 *     matters, and it cannot happen, because the registrar's `addVerified` call would revert with
 *     `CountryBlocked` anyway.
 *
 * So: render `blocked` for the disabled options and the explanation beside them, and let the
 * server's answer overrule it when the two disagree.
 */

import countriesJson from "./countries.json";

/** One ISO 3166-1 entry. `reason` is present exactly when `blocked` is true. */
export interface Country {
  /** ISO 3166-1 numeric, 1..999 — the `uint16 country` the registry stores. */
  readonly numeric: number;
  /** ISO 3166-1 alpha-2, upper case. */
  readonly alpha2: string;
  /** English name, as ISO writes it ("Türkiye", "United States of America"). */
  readonly name: string;
  /** True when the deploy script seeds this code into the registry's blocklist. */
  readonly blocked: boolean;
  /** Why it is blocked, in a sentence fit to render next to a disabled option. */
  readonly reason: string | null;
}

interface RawCountry {
  numeric: number;
  alpha2: string;
  name: string;
  blocked?: boolean;
  reason?: string;
}

interface RawFile {
  generated_by: string;
  source: string;
  note: string;
  count: number;
  blocked_count: number;
  countries: RawCountry[];
}

const raw = countriesJson as RawFile;

/** Where the data came from, for a footnote under the select. */
export const COUNTRY_LIST_SOURCE = raw.source;

/** Every country, ascending by numeric code — the order the generated file is written in. */
export const COUNTRIES: readonly Country[] = raw.countries.map((entry) => ({
  numeric: entry.numeric,
  alpha2: entry.alpha2,
  name: entry.name,
  blocked: entry.blocked === true,
  reason: entry.reason ?? null,
}));

/** Every country, ascending by English name — the order a select should render. */
export const COUNTRIES_BY_NAME: readonly Country[] = [...COUNTRIES].sort((a, b) =>
  a.name.localeCompare(b.name, "en"),
);

const BY_NUMERIC: ReadonlyMap<number, Country> = new Map(
  COUNTRIES.map((country) => [country.numeric, country]),
);

const BY_ALPHA2: ReadonlyMap<string, Country> = new Map(
  COUNTRIES.map((country) => [country.alpha2, country]),
);

/**
 * The seed blocklist, as the deploy script writes it. Not the live one — see the module header.
 */
export const SEED_BLOCKED_COUNTRIES: readonly Country[] = COUNTRIES.filter(
  (country) => country.blocked,
);

/** The seed-blocked numeric codes, ascending. `[792, 840]`. */
export const SEED_BLOCKED_CODES: readonly number[] = SEED_BLOCKED_COUNTRIES.map(
  (country) => country.numeric,
).sort((a, b) => a - b);

export function getCountryByNumeric(numeric: number): Country | null {
  return BY_NUMERIC.get(numeric) ?? null;
}

export function getCountryByAlpha2(alpha2: string): Country | null {
  return BY_ALPHA2.get(alpha2.trim().toUpperCase()) ?? null;
}

/** True when `value` is an ISO 3166-1 numeric code this list knows. */
export function isKnownCountryCode(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && BY_NUMERIC.has(value);
}

/**
 * The range `IdentityRegistry._checkCountry` accepts. 0 is rejected on chain because an unset
 * country would otherwise slip past a blocklist that only ever stores real codes.
 */
export function isCountryCodeInContractRange(value: number): boolean {
  return Number.isInteger(value) && value >= 1 && value <= 999;
}

/** True when the *seed* blocklist contains this code. The chain can add to it; see the header. */
export function isSeedBlockedCountry(numeric: number): boolean {
  return getCountryByNumeric(numeric)?.blocked === true;
}

/**
 * The reason a code is seed-blocked, or `null`. Used for the disabled-option explanation and as
 * the fallback reason when the chain refuses a country it has blocked since deployment.
 */
export function seedBlockedReason(numeric: number): string | null {
  const country = getCountryByNumeric(numeric);
  return country?.blocked ? country.reason : null;
}

/** `"Germany (276)"` — for a log line or a confirmation sentence. */
export function describeCountry(numeric: number): string {
  const country = getCountryByNumeric(numeric);
  return country ? `${country.name} (${country.numeric})` : `country ${numeric}`;
}
