import { existsSync, readFileSync, writeFileSync } from "node:fs";

let output = "// Generated by pnpm sync:contracts from Foundry artifacts.\n";
for (const name of ["IdentityRegistry", "HBToken", "MockUSDC"]) {
  const artifact = JSON.parse(
    readFileSync(`contracts/out/${name}.sol/${name}.json`, "utf8"),
  );
  output += `export const ${name[0]!.toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync("packages/config/abi.ts", output);
const deployments: Record<string, unknown> = {};
for (const name of ["arc-testnet", "base-sepolia", "local"]) {
  const path = `deployments/${name}.json`;
  if (existsSync(path))
    deployments[name] = JSON.parse(readFileSync(path, "utf8"));
}
writeFileSync(
  "packages/config/deployments.json",
  JSON.stringify(deployments, null, 2) + "\n",
);
console.log("Generated typed contract ABIs.");
